// Facade — implementation split into src/lib/ai/ (v2.1.0 refactor).
// Public API preserved; import paths remain @/lib/ai-decision-engine.
export * from "./ai/types"
export * from "./ai/helpers"
export * from "./ai/technical-synthesis"
export * from "./ai/news-analysis"
export * from "./ai/sentiment"
export * from "./ai/risk-context"
export * from "./ai/signal-tracking"
export * from "./ai/reasoning"
export * from "./ai/decision-core"
export * from "./ai/consensus"
export * from "./ai/batch"
export * from "./ai/trackers"
export * from "./ai/config"
export * from "./ai/self-learning"
